### ISSUE TITLE
In react view, screening status filter option "no status" results in No results found.

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2423]
Same filter in the non-react view lists submissions correctly.

**Comment by vimal1083** [comment]
@danblah, I have fixed this bug on 26th May, 2021. May I know the last deployed date on testing?

**Comment by Parbhat** [comment]
@vimal1083 The test environment uses this branch https://github.com/HyphaApp/hypha/tree/test

**Comment by vimal1083** [comment]
@danblah Could you share the screenshot of the error?

**Comment by danblah** [comment]
See screen capture. Still having this issue.
https://user-images.githubusercontent.com/620336/124655407-cc943a80-de6d-11eb-9c87-02705f1a854d.mp4
